services:

  postgres:
    image: postgres:16-alpine
    container_name: freshcart-db
    environment:
      POSTGRES_DB: freshcart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./checkout-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - freshcart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d freshcart"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  checkout-api:
    build:
      context: ./checkout-api
      dockerfile: Dockerfile
    container_name: freshcart-api
    environment:

      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/freshcart
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - freshcart-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: freshcart-storefront
    ports:
      - "8080:8080"
    networks:
      - freshcart-network
    depends_on:
      - checkout-api
    restart: unless-stopped


volumes:
  postgres-data:

networks:
  freshcart-network:
    driver: bridge
